---
name: shubham
address: nagpur
...
---
class: linux
fees: 10000
...

fruit:
  - mango
  - banana
  - apple
color:
  white
  black
  silver
  gold


information:
  - name: shubham
  - address: nagpur

